### ISSUE TITLE
ProposedTransaction.__init__ should convert `tag` value to a `Tag` object

### ISSUE THREAD

**Issue by lukzmu** [iotaledger/iota.lib.py#100]
TryteString.from_string has bad padding. If you run:

```
tag = TryteString.from_string("tagname")
```
It won't return a string that is 27 characters long, which creates issues with other functions. Need to make ugly hacks, that add 9's up to the 27 lenght requirement.

Example structure it was generating issues with:

```
transfers=[

                ProposedTransaction(

                    address=Address("JEMEHHS9EEASH9UFOLYAKBCTNKGBADCLTKCEOEKPZVILIGTZOGYMFMWKQABVVNKHGHBHTJNRVDDMMUQOX"),

                    value=0

                ),

                ProposedTransaction(

                    address=Address("LORKNNVSBTILWAUZBK9RTMVFPJOWAU9KOIINNGYISJQ9P9AFBFH9OJNXBILBFRPVHGVNIBB9LYGUHCESB"),

                    value=0,

                    message=TryteString.from_string("First transaction"),

                    tag=TryteString.from_string("xCarx")

                )

    ],
```

**Comment by todofixthis** [comment]
Hey @lukzmu `ProposedTransaction` should automatically convert the `TryteString` into a `Tag` object, which automatically pads the sequence to 27 trytes.

Alternatively, try using `Tag` instead of `TryteString`, or in a pinch, you can specify a padding length when initialising a `TryteString`.

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.5
Thanks @rpitonak !
