### ISSUE TITLE
Chop off checksum when using address in core commands

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/iota.lib.py#101]
Example:
```python
In [1]: from iota import Address

In [2]: addy = Address('WLVZXWARPSYCWJMBZJGXHUOVYBVCEKMNQDMXHCAEJZFLFLMHFYYQQSSLVYWAZWESKXZOROLU9OQFRVDEWCHKKXPWGY')

In [3]: api.get_balances([addy])
iota.adapter.BadApiResponse: 400 response from node: Invalid addresses input
```

Workaround:
```python
In [4]: api.get_balances([addy.address])
Out[4]:
{'balances': [0],
 'duration': 9,
 'milestone': Address(b'GNKYBMEKZFBYEQXINYTUGLGVSYCMRBBYDCWJ9KMJUTVMNDUVZQKGJK9RPBGTLWPYYERSLBPQBUTRZ9999'),
 'milestoneIndex': 286176}
```

I feel like PyOTA should do this automatically — there are a lot of use cases that involve generating addresses with checksums; it would get pretty unwieldy to have to remember to extract just the address when calling certain commands.

**Comment by plenarius** [comment]
Gonna look into tackling this over the next week.

**Comment by plenarius** [comment]
Okay, the only two core commands that take addresses as arguments are `get_balances` and `find_transactions`. My first shot at this has me massaging the addresses in a new `_prepare_requests` for both `GetBalancesCommand` and `FindTransactionsCommand` with such:

```python
def _prepare_request(self, request):
    no_checksum_addresses = []

    for addy in request['addresses']:
      no_checksum_addresses.append(Address(addy.address))

    request['addresses'] = no_checksum_addresses

    return self._apply_filter(
      value           = request,
      filter_         = self.get_request_filter(),
      failure_message = 'Request failed validation',
    )
```
Sound like an okay approach?

**Comment by todofixthis** [comment]
Could we integrate this functionality directly into the filters?  That way, we don't have to worry about copy-pasting that code if we add new commands in the future (I'm aware of at least 2 that are coming in the next IRI release).

Take a look at these guys and see if it makes sense to implement a filter:
https://github.com/iotaledger/iota.lib.py/blob/develop/iota/filters.py

**Comment by plenarius** [comment]
Yep I can certainly do that, looked all into that already but thought it may be overkill. Will see what I come up with.

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.3
