### ISSUE TITLE
Write documentation about multisig

### ISSUE THREAD

**Issue by QuantumDamage** [iotaledger/iota.lib.py#103]
This example might be useful: https://github.com/iotaledger/iota.lib.py/blob/develop/examples/multisig.py

**Comment by QuantumDamage** [comment]
I will work on that.

**Comment by todofixthis** [comment]
Thanks @QuantumDamage!

**Comment by todofixthis** [comment]
Additional resources:
- https://github.com/iotaledger/wiki/blob/master/multisigs.md

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.3
