### ISSUE TITLE
send_transfer example fails 400

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [iotaledger/iota.lib.py#104]
Hi,

I'm running iri 1.4.1.2 and was trying to run the `send_transfer.py` example (py3). It terminates with 
```
iota.adapter.BadApiResponse: 400 response from node: This operations cannot be executed: The subtangle has not been updated yet.
```
What do I have to do to update the subtangle? Do I HAVE to have neighbors to run the examples?

Output of the `hello_world.py`:
```
Hello http://localhost:14265/!
{'appName': 'IRI',
 'appVersion': '1.4.1.2',
 'duration': 10,
 'jreAvailableProcessors': 4,
 'jreFreeMemory': 309029696,
 'jreMaxMemory': 1843920896,
 'jreTotalMemory': 763887616,
 'jreVersion': '1.8.0_144',
 'latestMilestone': TransactionHash(b'999999999999999999999999999999999999999999999999999999999999999999999999999999999'),
 'latestMilestoneIndex': 243000,
 'latestSolidSubtangleMilestone': TransactionHash(b'999999999999999999999999999999999999999999999999999999999999999999999999999999999'),
 'latestSolidSubtangleMilestoneIndex': 243000,
 'neighbors': 0,
 'packetsQueueSize': 0,
 'time': 1512461259644,
 'tips': 0,
 'transactionsToRequest': 0}
```
Thanks for your help in advance!

Best regards

Marius

PS.: for the sake of completeness here the full error stack:
```
Traceback (most recent call last):
  File "send_transfer.py", line 42, in <module>
    message = TryteString.from_string('Hello!'),
  File "/usr/local/lib/python3.4/dist-packages/PyOTA-2.0.2-py3.4.egg/iota/api.py", line 845, in send_transfer
    minWeightMagnitude  = min_weight_magnitude,
  File "/usr/local/lib/python3.4/dist-packages/PyOTA-2.0.2-py3.4.egg/iota/commands/__init__.py", line 126, in __call__
    self.response = self._execute(self.request)
  File "/usr/local/lib/python3.4/dist-packages/PyOTA-2.0.2-py3.4.egg/iota/commands/extended/send_transfer.py", line 52, in _execute
    trytes              = pt_response['trytes'],
  File "/usr/local/lib/python3.4/dist-packages/PyOTA-2.0.2-py3.4.egg/iota/commands/__init__.py", line 126, in __call__
    self.response = self._execute(self.request)
  File "/usr/local/lib/python3.4/dist-packages/PyOTA-2.0.2-py3.4.egg/iota/commands/extended/send_trytes.py", line 42, in _execute
    gta_response = GetTransactionsToApproveCommand(self.adapter)(depth=depth)
  File "/usr/local/lib/python3.4/dist-packages/PyOTA-2.0.2-py3.4.egg/iota/commands/__init__.py", line 126, in __call__
    self.response = self._execute(self.request)
  File "/usr/local/lib/python3.4/dist-packages/PyOTA-2.0.2-py3.4.egg/iota/commands/__init__.py", line 154, in _execute
    return self.adapter.send_request(request)
  File "/usr/local/lib/python3.4/dist-packages/PyOTA-2.0.2-py3.4.egg/iota/adapter/__init__.py", line 301, in send_request
    return self._interpret_response(response, payload, {codes['ok']})
  File "/usr/local/lib/python3.4/dist-packages/PyOTA-2.0.2-py3.4.egg/iota/adapter/__init__.py", line 438, in _interpret_response
    'response': decoded,
iota.adapter.BadApiResponse: 400 response from node: This operations cannot be executed: The subtangle has not been updated yet.
```

**Comment by HerrMuellerluedenscheid** [comment]
The reason seems to be lacking neighbors.

However, I find the error message ` The subtangle has not been updated yet` a bit misleading. How about `The subtangle is not synchronized, yet`? I think `update` indicates rather a software issue whereas `synchronize` indicates a networking problem, which points more in the right direction.

**Comment by todofixthis** [comment]
Hey @HerrMuellerluedenscheid aye, I agree; the error message could probably be clarified.

This message comes [directly from the IRI](https://github.com/iotaledger/iri/blob/v1.4.1.2/src/main/java/com/iota/iri/service/API.java#L254-L257), so the IRI bug tracker is the best place to report this.

That said, I think this error is only relevant so long as the Coordinator is operating — as soon as the COO gets shut down, there will be no "canonical" Tangle that the node has to synchronise with.

**Comment by damianme** [comment]
Hi @todofixthis I believe I have a similar error:
`BadApiResponse: 400 response from node: Tip not found: 999999999999999999999999999999999999999999999999999999999999999999999999999999999`
Does it mean that testnet node is faulty?
Here is my code:
https://github.com/QuantumDamage/iota.lib.py/blob/develop/tutorials/helloworld/helloworld.ipynb

**Comment by todofixthis** [comment]
Hey Damian.  Awesome tutorial; I love where you're going with that!

The error in question is coming from a `getBalances` request:

```
~/anaconda3/envs/PyOTA/lib/python3.6/site-packages/iota/commands/extended/prepare_transfer.py in _execute(self, request)
     63 
     64         gb_response = GetBalancesCommand(self.adapter)(
---> 65           addresses = [i.address for i in proposed_inputs],
     66         )
     67 
```

Since PyOTA doesn't send tips as part of this request, I'm inclined to think that the issue here is on the IRI side of things (and also that the IRI should be sending back a 500 response, not a 400).

**Comment by damianme** [comment]
@todofixthis Thanks!
Ok, but I believe we have two problems here. One is 500/400 status (thanks for posting to IRI bug tracker btw.) and second is that I think that when I posted this issue, testtnet node wasn't correctly operational. Now (about 24hours later) I have the correct response. My hint of faulty node is 99999..... in **latestSolidSubtangleMilestone**
This is comparison of responses from **api.get_node_info()**:

<img width="1440" alt="screen shot 2018-02-16 at 8 56 41 am" src="https://user-images.githubusercontent.com/35031166/36298250-76e9b276-12f7-11e8-9c45-167c59cd69ad.png">
 
Does it make sense?
If yes maybe I should add check and description that if there are 999999... there, there is need to search for ohter node?

**Comment by todofixthis** [comment]
That's a really interesting idea.  I think that we could turn that into its own feature:

- A wrapper that, given a collection of node URIs, will (randomly? round-robin? ...) select a node for each API request.
    - A "health check" or similar feature that will [temporarily?] drop a node from the collection if it is determined to be unhealthy.

**Comment by damianme** [comment]
@todofixthis Yes, that would be useful for people which are getting started with IOTA. Later when they will be experienced they will be able to change to custom testnet or mainnet nodes without a problem, but at the beginning, this could save them a lot of frustration and time.

**Comment by anistark** [comment]
I'm still getting this even with `iri 1.4.2.4`. Has there been any developments or workarounds for this?

**Comment by HerrMuellerluedenscheid** [comment]
Does your iri have neighbors? Is it synchronized?

**Comment by MHKhalil** [comment]
@HerrMuellerluedenscheid is it necessary to have neighbors to send transaction??

**Comment by anistark** [comment]
@MHKhalil The node that your client lib is connected with must have neighbours.
You can also use one of the publicly available tangle nodes.

**Comment by MHKhalil** [comment]
@anistark thank you for your response :) 
I have already used the solution of public nodes but now I am trying to interact with the Tangle using a private IRI node.
in fact, I have a node that works on a docker container and i am using a virtual private network (VPN) is it possible to have neighbors with this node? 
Thanks for your help in advance!! :)

**Comment by anistark** [comment]
@MHKhalil 👍 Ya sure. You can add neighbours. Ask anybody on the fullnode channel on iota discord server and there'll be folks to help you out. I closed my node few months ago or would have added you as neighbour. :)

**Comment by MHKhalil** [comment]
@anistark  thanks a lot 👍 :)
