### ISSUE TITLE
Add `timeout` argument to `HttpAdapter.__init__`

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/iota.lib.py#105]
Right now, `iota.adapter.HttpAdapter` uses `socket.getdefaulttimeout` to set the timeout for each HTTP request.<sup>1</sup>

However, applications really should have the flexibility to define a timeout specific to IOTA API requests (and even potentially to set different timeouts per `iota.api.Iota` instance in the same application).

Add a `timeout` argument to `HttpAdapter.__init__`.  If not specified it should default to `None`<sup>2</sup>.

When `iota.adapter.HttpAdapter._send_http_request` runs, it should use the following logic to determine the timeout value:

- If `kwargs['timeout']` is set, use that.
- Else if `self.timeout` is set, use that.
- Else use `socket.getdefaulttimeout()`.

<sup>1</sup> Technically, this can be set on a per-request basis, but it is at such a low level that regular applications won't be able to use it.

<sup>2</sup> **Important:** the default value for `timeout` should be `None`, **not** `socket.getdefaulttimeout()`.  That way, if the application calls `socket.setdefaulttimeout()` at any point after creating the instance, `HttpAdapter` doesn't cache the stale value.

**Comment by szepnapot** [comment]
Can I take this? :)

**Comment by todofixthis** [comment]
Hey @szepnapot go pfhor it! 😺

**Comment by jinnerbichler** [comment]
Created a PR #110

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.4.

Thanks Johannes!!
