### ISSUE TITLE
NodeUri(f.BaseFilter) does not support tcp connections

### ISSUE THREAD

**Issue by danielfaust** [iotaledger/iota.lib.py#111]
https://github.com/iotaledger/iota.lib.py/blob/e345de981829a36ceaccf3862835c0dd28486950/iota/filters.py#L62

It's not possible to add / remove nodes when the tcp protocol is used.

**Comment by todofixthis** [comment]
Thanks for reporting this @danielfaust !  I agree that PyOTA is probably a bit too opinionated about what constitutes a node URI.  If IRI (or for that matter, custom IOTA node software) supports TCP neighbour connections, then we should definitely support that.

**Comment by laumair** [comment]
@todofixthis Has anybody picked this up yet?

**Comment by todofixthis** [comment]
@laumair not to my knowledge.  Or at least, I haven't seen any pull requests for it yet.

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.4

Thank you for reporting this issue!
