### ISSUE TITLE
Implement checkConsistency API

### ISSUE THREAD

**Issue by scottbelden** [iotaledger/iota.lib.py#113]
This API was added [recently](https://github.com/iotaledger/iri/pull/399) and exists in the java script library. Any problems with adding it to the python one? If not, I don't mind taking a stab at it.

**Comment by scottbelden** [comment]
The PR has a commit with some tests (pretty much copy/pasted from `get_latest_inclusion_test` as they were pretty similar. The JS library just says [returns whether the given tail is consistent](https://github.com/iotaledger/iota.lib.js/blob/433f5d37a684abf875aaa6f1fb97082ab06218f0/lib/api/apiCommands.js#L227)

**Comment by todofixthis** [comment]
Oh.  Well, that's... err, descriptive? 😸 

I feel like we could make the description more helpful by including information about when an application might need to call `checkConsistency`, but I'm still trying to wrap my brain around the latest API changes myself, so perhaps nobody knows 😆

**Comment by scottbelden** [comment]
I'm honestly not sure either... I just wanted to write a script that would `reattach`/`promote` all of my unconfirmed transactions and was basically just copying what the JS library did (without fully understanding exactly what the API does)

**Comment by plenarius** [comment]
I see from an older commit the comments about this method stated this, might be helpful

> Should tell us if the subtangle below {tail} resolves to a consistent ledger

https://github.com/iotaledger/iota.lib.js/commit/ec5ba38eea5ddc1d210054a8e91ff6b110f8e3c5#diff-bb621303422b11c2aa40fb05b806c045L1937

**Comment by scottbelden** [comment]
Thanks. I included this as part of the updated docstring.

**Comment by todofixthis** [comment]
Scheduled for release: v2.0.3

Thanks @scottbelden !!
