### ISSUE TITLE
Address with checksum doesnt seem to work in find_transactions

### ISSUE THREAD

**Issue by chriamue** [iotaledger/iota.lib.py#116]
Getting following error when I try to find a transaction with an address with checksum:
Traceback (most recent call last):
  File "Test.py", line 49, in test_s_sent_to_r
    transactions = api.find_transactions(addresses = addresses)
  File "/usr/local/lib/python3.5/dist-packages/iota/api.py", line 235, in find_transactions
    approvees = approvees,
  File "/usr/local/lib/python3.5/dist-packages/iota/commands/__init__.py", line 126, in __call__
    self.response = self._execute(self.request)
  File "/usr/local/lib/python3.5/dist-packages/iota/commands/__init__.py", line 154, in _execute
    return self.adapter.send_request(request)
  File "/usr/local/lib/python3.5/dist-packages/iota/adapter/__init__.py", line 301, in send_request
    return self._interpret_response(response, payload, {codes['ok']})
  File "/usr/local/lib/python3.5/dist-packages/iota/adapter/__init__.py", line 438, in _interpret_response
    'response': decoded,
iota.adapter.BadApiResponse: 400 response from node: Invalid addresses input

Code:
addresses = [Address('ACESICDEEKYSTSBBKCXHGGBTFR9FGOMOWDAQJEI9ECTBBMKRFLMGAJXOQGSOOMODKPJKANVSEGIEYNNNAILGUG9RUX')]
api = Iota(self.uri)
transactions = api.find_transactions(addresses = addresses)

Address without checksum works: 'ACESICDEEKYSTSBBKCXHGGBTFR9FGOMOWDAQJEI9ECTBBMKRFLMGAJXOQGSOOMODKPJKANVSEGIEYNNNA'

The IOTA Wallet gives addresses with checksum so it would be cool if this function automatically removes checksum and sends the address without checksum to the node.

**Comment by todofixthis** [comment]
Hey @chriamue thanks for reporting this!

A fix for this issue will be released with v2.0.3 later this week as part of https://github.com/iotaledger/iota.lib.py/issues/101

I'm just waiting for closure on https://github.com/iotaledger/iota.lib.py/issues/113 before preparing the release.

If you'd like to verify the fix, you can install the `develop` branch of PyOTA:
```
pip install -e 'git+https://github.com/iotaledger/iota.lib.py.git@develop#egg=PyOTA'
```

Note:  Although we are close to the next release, and the `develop` branch has really good test coverage, it is still technically pre-release software.  Please exercise extreme caution before using pre-release code on mainnet.
