### ISSUE TITLE
REPL entry point conflicts with iota official cli-app

### ISSUE THREAD

**Issue by plenarius** [iotaledger/iota.lib.py#122]
The command `iota-cli` defined [here](https://github.com/iotaledger/iota.lib.py/blob/9389d1723be4beae486f6614cc068ac4b1ad1654/setup.py#L51) is used by the [cli-app](https://github.com/iotaledger/cli-app/blob/e5ab77b00e78e605e24d44fb6e60632ac0fba0e8/package.json#L30). Installation of pyota overwrites executable in /usr/local/bin

Suggest change to `pyota-cli`, can do PR if agreed.

**Comment by todofixthis** [comment]
Good idea.  I think it makes sense to create a namespace for PyOTA to prevent conflicts like this.

Too bad PyOTA isn't more popular; then someone would have logged an issue on the cli-app issue tracker instead 😹

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.4

Thanks James!!
