### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by awea009** [iotaledger/iota.lib.py#123]
Hi, im trying to install pyota but i cant, that was my issue:

> Obtaining file:///home/gosen/Escritorio/python/pyota/iota.lib.py
> Collecting filters (from PyOTA==2.0.3)
>   Using cached filters-1.3.2-py2.py3-none-any.whl
> Collecting pysha3 (from PyOTA==2.0.3)
>   Using cached pysha3-1.0.2-cp27-cp27mu-manylinux1_x86_64.whl
> Collecting requests[security]>=2.4.1 (from PyOTA==2.0.3)
>   Using cached requests-2.18.4-py2.py3-none-any.whl
> Collecting six (from PyOTA==2.0.3)
>   Using cached six-1.11.0-py2.py3-none-any.whl
> Collecting typing (from PyOTA==2.0.3)
>   Using cached typing-3.6.2-py2-none-any.whl
> Collecting py2casefold; python_version < "3.0" (from filters->PyOTA==2.0.3)
>   Using cached py2casefold-1.0.1-py2.py3-none-any.whl
> Collecting regex (from filters->PyOTA==2.0.3)
> Collecting python-dateutil (from filters->PyOTA==2.0.3)
>   Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
> Collecting class-registry (from filters->PyOTA==2.0.3)
>   Using cached class_registry-2.1.0-py2.py3-none-any.whl
> Collecting pytz (from filters->PyOTA==2.0.3)
>   Using cached pytz-2017.3-py2.py3-none-any.whl
> Collecting idna<2.7,>=2.5 (from requests[security]>=2.4.1->PyOTA==2.0.3)
>   Using cached idna-2.6-py2.py3-none-any.whl
> Collecting urllib3<1.23,>=1.21.1 (from requests[security]>=2.4.1->PyOTA==2.0.3)
>   Using cached urllib3-1.22-py2.py3-none-any.whl
> Collecting certifi>=2017.4.17 (from requests[security]>=2.4.1->PyOTA==2.0.3)
>   Using cached certifi-2017.11.5-py2.py3-none-any.whl
> Collecting chardet<3.1.0,>=3.0.2 (from requests[security]>=2.4.1->PyOTA==2.0.3)
>   Using cached chardet-3.0.4-py2.py3-none-any.whl
> Collecting cryptography>=1.3.4; extra == "security" (from requests[security]>=2.4.1->PyOTA==2.0.3)
>   Using cached cryptography-2.1.4-cp27-cp27mu-manylinux1_x86_64.whl
> Collecting pyOpenSSL>=0.14; extra == "security" (from requests[security]>=2.4.1->PyOTA==2.0.3)
>   Using cached pyOpenSSL-17.5.0-py2.py3-none-any.whl
> Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.3.4; extra == "security"->requests[security]>=2.4.1->PyOTA==2.0.3)
>   Using cached cffi-1.11.2-cp27-cp27mu-manylinux1_x86_64.whl
> Collecting enum34; python_version < "3" (from cryptography>=1.3.4; extra == "security"->requests[security]>=2.4.1->PyOTA==2.0.3)
>   Using cached enum34-1.1.6-py2-none-any.whl
> Collecting asn1crypto>=0.21.0 (from cryptography>=1.3.4; extra == "security"->requests[security]>=2.4.1->PyOTA==2.0.3)
>   Using cached asn1crypto-0.24.0-py2.py3-none-any.whl
> Collecting ipaddress; python_version < "3" (from cryptography>=1.3.4; extra == "security"->requests[security]>=2.4.1->PyOTA==2.0.3)
> Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.3.4; extra == "security"->requests[security]>=2.4.1->PyOTA==2.0.3)
> Installing collected packages: six, py2casefold, regex, python-dateutil, typing, class-registry, pytz, filters, pysha3, idna, urllib3, certifi, chardet, pycparser, cffi, enum34, asn1crypto, ipaddress, cryptography, pyOpenSSL, requests, PyOTA
>   Found existing installation: PyOTA 2.0.3
>     Uninstalling PyOTA-2.0.3:
>       Successfully uninstalled PyOTA-2.0.3
>   Running setup.py develop for PyOTA
>     Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/home/gosen/Escritorio/python/pyota/iota.lib.py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=:
>     
>     ----------------------------------------
>   Rolling back uninstall of PyOTA
> Violación de segmento (`core' generado)

I was searching if that question exists and it does exists here:[https://github.com/iotaledger/iota.lib.py/issues/79](https://github.com/iotaledger/iota.lib.py/issues/79)
So i tryied:
pip install --no-binary ':all:' pyota 
and it apparently worked, but after that when i try to import Iota from iota i had that :

> from iota import Iota
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: cannot import name Iota

so, what i have to do?
thanks for reading and sorry for my english!

**Comment by todofixthis** [comment]
Hola @awea009!  No te preocupes — en realidad, tu inglés es probablemente mejor que mi español 😸 

Thanks for reporting this issue!  Some ideas:

- Segfault during installation often occurs when compiling something.  PyOTA itself doesn't have any compiled modules, but some of its dependencies do.  Try installing each of these packages one-by-one, to see if they are causing the problem:
    - `cffi`
    - `cryptography`
    - `pysha3`
- Sometimes packages don't work correctly if they are installed at system-level.  Try installing PyOTA into a [virtualenv](http://docs.python-guide.org/en/latest/dev/virtualenvs/).

Give these a try, and let me know what you find out.

Suerte!

**Comment by awea009** [comment]
Thx for the answer @todofixthis!
I've resolved the problem uninstalling pyota and pyota ccurl, then i tryied again : "pip install --no-binary ':all:' pyota" and it worked. 
Thx again!

**Comment by todofixthis** [comment]
Awesome!  Glad to hear you got it sorted, and thanks for posting your solution!
