### ISSUE TITLE
Add authentication headers to HTTP requests when IRI node is running with `--remote-auth`

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [iotaledger/iota.lib.py#129]
Hi again, 

I saw the same question unanswered [on reddit ](https://www.reddit.com/r/Iota/comments/6yalf2/how_does_remoteauth_work/), so I thought I approach you directly. How can I connect to my full node when [`--remote-auth`](https://github.com/iotaledger/iri/#command-line-options) is active? I searched through the code but couldn't get the point. Is it not yet implemented or 'hidden' in a wrapping call? If it is not implemented and I wanted to give it a shot, where would I have to start digging into the code? My first naive guess would be to extend the `BaseCommand`.

Greetings from Potsdam

Marius
 

PS.: I asked on slack as well but didn't get a response, yet. And also others might sooner or later have the same question.

**Comment by HerrMuellerluedenscheid** [comment]
Thanks to Nuriel Shem-Tov on slack I was able to use remote authentication by modifying the http headers of the http adapter. Here are the essentials:

```
from base64 import b64encode

adapter = HttpAdapter(
  uri = u'http://localhost:14700',
)

user_pass = b64encode(b'username:PASSWORD').decode('ascii')
adapter.DEFAULT_HEADERS[u'Authorization'] = u'Basic %s' % user_pass

api = Iota(
    adapter=adapter,
    seed = b'DMSWNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
```

I'm not sure though if there is a more elegant way. Modifying _default_ header attributes seems a little workaround-ish. Should there be an 'extra_header' argument to the `BaseAdapter`?

Apart from that, the authentication can also be done right in the url as e.g. [here](https://stackoverflow.com/questions/2716990/http-basic-authentication-credentials-passed-in-url-and-encryption). But I found it a little more elegant to do it the first way.

**Comment by todofixthis** [comment]
Hey @HerrMuellerluedenscheid thanks for reporting this!  I think this is a shortcoming in PyOTA — we should definitely support this out-of-the-box, no hacking necessary (:

**Comment by todofixthis** [comment]
Hey @HerrMuellerluedenscheid out of curiosity, does the adapter work if username/password are included in the node URI?

E.g.:

```python
api = Iota("http://username:password@localhost:14265")
```

**Comment by todofixthis** [comment]
Sweet.  I like that you included a documentation update in your PR.  What do you say to this:  Let's keep the existing functionality then (https://www.python.org/dev/peps/pep-0020/ — "There should be one-- and preferably only one --obvious way to do it."), but include the auth info/example in the documentation.

**Comment by HerrMuellerluedenscheid** [comment]
I agree. Explicit is better than implicit, though :) However, that's probably the cleaner way to go. Going to update the pr on Monday!

**Comment by HerrMuellerluedenscheid** [comment]
Basic authentication via URLs is deprecated [(Wikipedia)](https://en.wikipedia.org/wiki/Basic_access_authentication#URL_encoding) and disabled in some browsers (e.g. [firefox](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#Access_using_credentials_in_URL)), as I just found out. So, should we stick to the URL encoded version or better use python.request.auth module?

**Comment by todofixthis** [comment]
Good question.  I think that depends on how the `requests` library handles it.

I had a peek at the [documentation](http://docs.python-requests.org/en/master/user/authentication/#basic-authentication), and I can't find any mention of basic auth via URLs, so maybe we should add an explicit `auth` parameter after all.

lol want to open that pull request back up? 😸 

Sorry for all the back-and-forth, but I do like the way you're thinking about this issue; auth is kind of a big deal (most IRI nodes probably aren't using HTTPS anyway, but that's a separate issue 😸 ), so I think it's important that we get this right.

**Comment by HerrMuellerluedenscheid** [comment]
Nah, I will just update the request #142 later today. I deleted the other PR/branch after a nasty rebase which uglified git's history :) 
No worries about the hassle. I'm glad to help :+1:

**Comment by todofixthis** [comment]
Roger that.  Thanks Marius!!

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.4.

Thanks Marius!!
