### ISSUE TITLE
api.get_tips()['hashes'] contains Addresses instead of TransactionHashes

### ISSUE THREAD

**Issue by schrotti264** [iotaledger/iota.lib.py#130]
```python3
import iota
api = iota.api.Iota('http://localhost:14265')
tips = api.get_tips()
hashes = tips['hashes']

print(type(hashes[0]))

# result is <class 'iota.types.Address'>
```

Bug is probably somewhere [here](https://github.com/iotaledger/iota.lib.py/blob/e345de981829a36ceaccf3862835c0dd28486950/iota/commands/core/get_tips.py#L45)  in line 45.

**Comment by todofixthis** [comment]
Hey @schrotti264 thank you for reporting this issue, and for resoarching the cause!  I think you're right on the money; the response filter is coercing the result to the wrong type.

This should be quick to fix; I'll add this to the list for the next release.

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.4

Thanks for reporting this issue!
