### ISSUE TITLE
Do we need the java app ?

### ISSUE THREAD

**Issue by olymk2** [iotaledger/iota.lib.py#141]
Do you actually need to be running the java software to use this library ?

And if so will this always be the case, would like to play around with the library but the requirement on java is making me hesitant.

**Comment by HerrMuellerluedenscheid** [comment]
You will need to have access to a node e.g. to attach transactions to the tangle. However, there are public nodes that allow you execute some requests.
E.g. you can run the `hello_world.py` example on one of the public nodes:

     python hello_world.py --uri=https://potato.iotasalad.org:14265

**Comment by olymk2** [comment]
Thats good to know, but if you want to do a transaction on an embedded device you could use micro python but this sort of file would not have the memory to run java so how would it work if the intention is we can use iota for the internet of things style devices ?

**Comment by HerrMuellerluedenscheid** [comment]
In that case you would still need a server running the IRI which allows your IOT devices to execute `attachToTangle` which would be sent from the python library on those devices to that node.
Checkout the [Sandbox Adapter](https://pyota.readthedocs.io/en/latest/adapters.html) which can be used for development and behaves like a full node (as far as I know - I haven't used it myself).

**Comment by todofixthis** [comment]
Hey @olymk2 you may be interested in #139 (:

**Comment by olymk2** [comment]
@todofixthis thanks for the link looks promising :)

**Comment by xie4991** [comment]
If the amount of traffic is large enough, it is ok.
