### ISSUE TITLE
Promote not possible?

### ISSUE THREAD

**Issue by chrisoro** [iotaledger/iota.lib.py#144]
I'm using the develop branch (as of now, latest commit: 033d6ecfd5da347fcf977021d0ea7745ed7008f8)

When connecting to nodes that use iri 1.4.1.6 `api.helpers.is_promotable(tx.hash)` and therefore `api.promote_transaction(tx.hash, depth)` are working.

When connecting to nodes that use iri 1.4.1.7RC `is_promotable` will always return false which makes `promote_transaction` throw 

> Transaction $TX_HASH% is not promotable. You should reattach first.

Might not eben be an issue with the pyapi but rather 1.4.1.7RC

Sadly, I'm not on my dev pc to debug myself but it's 100% reproducible on my end.

**Comment by chrisoro** [comment]
Can be closed. It seems my sample size auf 20 was not enough. Changed my script to autopromote random stuff and it worked on most tx.

**Comment by todofixthis** [comment]
Hey @chrisoro glad to hear you got it sorted, and thanks for posting your solution!  Post back if it gives you any more trouble, and we'll see if this needs to be escalated to the IRI team.
