### ISSUE TITLE
typo at python api documentation at function : is_reattachable()

### ISSUE THREAD

**Issue by maxmbed** [iotaledger/iota.lib.py#156]
There is a typo with the python lib documentation that confuse the reader. It tells software that the new transaction will be replay with **different seed** instead of **different one**

Python : 
https://github.com/iotaledger/iota.lib.py/blob/540668b31a3e17593572f44e57c8d21aa06617ee/iota/api.py#L951

JS : 
https://github.com/iotaledger/iota.lib.js/blob/a1b2e9e05d7cab3ef394900e5ca75fb46464e608/lib/api/api.js#L1824-L1825

**Comment by todofixthis** [comment]
Thanks for reporting this Maxime!  Aye, I agree that's a tad confusing; we should get that fixed.

This is a great starter issue for anyone who wants to contribute to PyOTA; I will mark this as "Help Wanted".

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.6.

Thanks @ribhu97!

**Comment by ribhu97** [comment]
No problem!
