### ISSUE TITLE
Add security_level parameter to get_inputs, prepare_transfer and send_transfer

### ISSUE THREAD

**Issue by lunfardo314** [iotaledger/iota.lib.py#172]
is there a reason why `get_inputs` always uses default security level to generate addresses? Maybe it makes sense to add parameter `security_level` for the sake of consistency? otherwise  `get_inputs` is useless for  `security_level`  1 and 3 .

**Comment by todofixthis** [comment]
Hey @lunfardo314 good catch; thanks for raising this issue!

That does look like an oversight; I agree that it makes sense to make security level configurable.

Hm.  I addition to `get_inputs`, we should probably also add a parameter to `prepare_transfer` and `send_transfer`.

**Comment by lunfardo314** [comment]
I created pull request for this issue, don't know how to reference it here

**Comment by lunfardo314** [comment]
so I do it this way: #173 ! Great, thanks!

**Comment by todofixthis** [comment]
Scheduled for release: v2.0.6

Thanks @lunfardo314 !!
