### ISSUE TITLE
Accumulated balance 0 is less than threshold 1

### ISSUE THREAD

**Issue by lapwat** [iotaledger/iota.lib.py#174]
I have an address with balance of 1 (transaction is confirmed) and the associated seed.
When I try to do a transfer of 1 iota to another address I get the following error : Accumulated balance 0 is less than threshold 1.

What is threshold ? Why can't I send the iota ?

Thank you,
lapwat

**Comment by todofixthis** [comment]
Hey lapwat.  Sorry to hear you're running into an issue here.  Let's look into this and figure out what's going on!

The threshold is the amount of IOTA that you're trying to spend (in this case, 1).

It appears that PyOTA is unable to find any addresses that it can use as inputs for your transaction.

Some reasons why this might be happening:

- After a snapshot, all of the transaction data are removed from the Tangle.  You will need to reattach your addresses in order for PyOTA to be able to find them again (see https://iota.stackexchange.com/a/735/283 for more info).
- Is PyOTA using the correct addresses?  Try iterating over the `iter_used_addresses()` function to see which addresses it is using for potential inputs.
- Are you setting the `security_level` value when generating addresses?  There is a known issue in PyOTA that prevents it from finding inputs with `security_level != 2` (see #172 for more info).
- Does the node have the correct balance for your address?  Try calling `api.get_balances([<address>])` to verify.

**Comment by lapwat** [comment]
I resolved my issue! I am using multiple apis and was using the wrong one to do the transfer ;)
Closing...

**Comment by todofixthis** [comment]
Awesome!  Glad to hear you were able to get it working!!
