### ISSUE TITLE
help get_new_address()

### ISSUE THREAD

**Issue by linuxMengfan** [iotaledger/iota.lib.py#180]
```python
gna_result = api.get_new_addresses(count=5)
addresses = gna_result['addresses']
```

The generated address cannot be bound in binance.

**Comment by todofixthis** [comment]
Hi @linuxMengfan could you provide more details about this issue?  What do you mean by "cannot be bound"?  Are you getting an error message?

**Comment by linuxMengfan** [comment]
api = Iota('http://node01.iotatoken.nl:14265', 'VMOI****ELJVQA')
      address = api.get_new_addresses(security_level=3, count=None, index=42)
{u'addresses': [Address('FUZEKAADSWTU9F9KUZFAILMTAFISNUQDERMAB99LPZBZNBONJOSQSUOSWFYZNIIYQPRL9QKZIMWOAGLGX')]}

Generated address not withdraw in "www.binance.com".

**Comment by todofixthis** [comment]
Hm.  I'm not sure I understand what is happening here.  Could you provide the error message that you get when you try to use that address?

This is a bit of a shot in the dark, but maybe the problem is that the addresses don't have checksum attached.  Try calling `get_new_addresses()` with `checksum=True`:

```python
address = api.get_new_addresses(security_level=3, count=None, index=42, checksum=True)
```

The resulting addresses will be 90 characters long, instead of 81.

**Comment by linuxMengfan** [comment]
@todofixthis  thank you.  I joined you as you said “checksum=True” 。Generated address withdraw in "www.binance.com" ! thank you.

**Comment by todofixthis** [comment]
Sweet!  Great to hear you got it working 😺

**Comment by linuxMengfan** [comment]
api = Iota('http://node01.iotatoken.nl:14265', 'VMOI****ELJVQA')# seed be 81 characters .
address = api.get_new_addresses(security_level=3, count=50, index=1, checksum=True)
info = self.api.get_account_data(start=0, stop=50)
The address generated by the two methods is not the same.
"address ="  resulting address is  be 90 characters .
"info = " resulting addresses in be 81 characters .

info = #{u'balance': 0, u'bundles': [], u'addresses': [Address('UWJKJIYTIAKGLGIYROIYC9I9IJZUTJAWXPNLVBLGFQCDEIUZTPFNKRWNXNUFHHR9GDENXRP9NDUWOYCMA'), Address('GZQOHMGT9VMNNNFTGPEXLTLKASJTVAQSFPZADVCDQXVRWSTHESKMJXFVFTGCCTKZMPAOFZAMHFUQYHWMY'),.........

**Comment by todofixthis** [comment]
This is expected behaviour; `get_account_data()` does not return checksummed addresses.

If you have an 81-characters address, and you'd like to get the 90-characters checksummed version, call its `with_valid_checksum()` methed.

```python
checksummed = [address.with_valid_checksum() for address in info['addresses']]
```

**Comment by linuxMengfan** [comment]
Many ways to address is not checksum. Caused a lot of mistakes。How do you set globally addresses is 'checksum' is be 90 characters  ? 
Run  test is `send_transfer.py` error :iota.adapter.BadApiResponse: Accumulated balance 0 is less than threshold 11.  Guess because there is no addresses is 'checksum' 。

**Comment by todofixthis** [comment]
Actually, most of the time the checksum is not needed.  In fact, IRI nodes actually treat an address with checksum as invalid.

The wallet adds a checksum, but this is only done to prevent copy-paste errors; in all other contexts, the checksum is not used/allowed.

---

WRT the error you're getting from `send_transfer.py`, make sure to set the `SEED1` variable to the seed that owns the address you're trying to spend from (`ADDRESS_WITH_CHECKSUM_SECURITY_LEVEL_2` is the address that you want to send the IOTAs to).

**Comment by linuxMengfan** [comment]
```python
"""
from iota import *

SEED1 = b"VMOICPPGGUYZBSHWGF9MOSBCNAARSYFMIJSSN9IYMPVYBFGTUTJNLP9LGVZTRMUFGWAXBMDXGJQELJVQA"
ADDRESS_WITH_CHECKSUM_SECURITY_LEVEL_2 = b"XOT9LAUKQXEIBPNKXFPBBGGCUZWYWL9OLAKXPVNVPDPWHFNEJMGFRRSFLJKOQFURYRHOMXUGF99HNIGSYQVX9EDCRW"

# Create the API instance.
api = \
    Iota(
        # URI of a locally running node.
        'http://node03.iotatoken.nl:15265',

        # Seed used for cryptographic functions.
        seed=SEED1
    )

# For more information, see :py:meth:`Iota.send_transfer`.
api.send_transfer(
    depth=100,

    # One or more :py:class:`ProposedTransaction` objects to add to the
    # bundle.
    transfers=[
        ProposedTransaction(
            # Recipient of the transfer.
            address=
            Address(
                ADDRESS_WITH_CHECKSUM_SECURITY_LEVEL_2,
            ),

            # Amount of IOTA to transfer.
            # This value may be zero.
            value=11,

            # Optional tag to attach to the transfer.
            tag=Tag(b'EXAMPLE'),

            # Optional message to include with the transfer.
            message=TryteString.from_string('Hello!'),
        ),
    ],
)
···
Error is  iota.adapter.BadApiResponse: Accumulated balance 0 is less than threshold 11 (``exc.context`` contains more information).
 address is balance FUZEKAADSWTU9F9KUZFAILMTAFISNUQDERMAB99LPZBZNBONJOSQSUOSWFYZNIIYQPRL9QKZIMWOAGLGXGDKRCHSKD = sed1 index 42 checksum .
is 19MI.

**Comment by todofixthis** [comment]
Hi @linuxMengfan I removed your seed from the example code.  Please do not post your seed publicly; whoever has your seed can spend your IOTAs.  I strongly urge you to generate a new seed and transfer all of your IOTAs to an address generated from the new seed ASAP.

---

I think I see what's going on now.

In the current version of PyOTA, `api.send_transfer()` uses security level 2 to generate addresses, inputs, etc.  However, the address that you want to use has security level 3.

In the current `develop` build of PyOTA, it is possible to specify a `security_level` when calling `send_transfer()`.

(`get_account_data()` always uses security level 2, however, even in the `develop` build; I'll log a thing to fix that; thanks for helping to identify this issue!)

Until that version is released, you can construct the transfer manually:

```python
from iota import Address, ProposedBundle, ProposedTransaction, Tag, TryteString

bundle = ProposedBundle([
    ProposedTransaction(
        # Recipient of the transfer.
        address=
            Address(
                ADDRESS_WITH_CHECKSUM_SECURITY_LEVEL_2,
            ),

        # Amount of IOTA to transfer.
        # This value may be zero.
        value=11,

        # Optional tag to attach to the transfer.
        tag=Tag(b'EXAMPLE'),

        # Optional message to include with the transfer.
        message=TryteString.from_string('Hello!'),
    ),
])

# Generate input address(es).
inputs = api.get_new_addresses(index=42, count=1, security_level=3)['addresses']

# Attach balance to each input.
gb_response = api.get_balances([i.address for i in inputs])
for i, balance in enumerate(gb_response['balances']):
  inputs[i].balance = balance

bundle.add_inputs(inputs)

# Generate a change address.
change_address = api.get_new_addresses(security_level=3)['addresses'][0]
bundle.send_unspent_inputs_to(change_address)

# Finalise and transmit the bundle.
bundle.finalize()
api.send_trytes(bundle.as_tryte_strings()
```
