### ISSUE TITLE
find_transactions requires tx hashes on iota.lib.py but it should require bundle hashes

### ISSUE THREAD

**Issue by oskyk** [iotaledger/iota.lib.py#186]
https://iota.readme.io/reference#findtransactions

According the reference this call should require list of bundle hashes not Transaction hashes

``` 
   :param bundles:
      List of transaction IDs.
```

**Comment by todofixthis** [comment]
Well spotted @oskyk!

**Comment by oskyk** [comment]
I have tried to change it here #189

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.7
Thanks @oskyk !!
