### ISSUE TITLE
Change `depth` to 3 in examples

### ISSUE THREAD

**Issue by Hribek25** [iotaledger/iota.lib.py#191]
https://github.com/iotaledger/iota.lib.py/blob/3f452a627233d413269381970058780a09215d64/examples/send_transfer.py#L22

**Comment by todofixthis** [comment]
Hey @Hribek25 good idea!  I just noticed all of the comments on Discord; we should get this changed over ASAP.

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.7
Thanks @Hribek25 !!
