### ISSUE TITLE
ImportError: cannot import name 'keccak_384'

### ISSUE THREAD

**Issue by xzcccc** [iotaledger/iota.lib.py#196]
I just run a IOTA demo by python3.5  (pyota==2.0.5), but its an error as follow in picture. However I can use python2.7 to run that demo.

![unknown](https://user-images.githubusercontent.com/26038528/42549289-f9a303e8-84fd-11e8-89dc-0a4aba33ede9.png)

How can I fix this error?
Thanks

**Comment by todofixthis** [comment]
Hey @xzcccc .  Were you able to resolve this issue?  Do post back if there's anything that we can assist with (:

**Comment by xzcccc** [comment]
@todofixthis Sorry for closing without comment. I solve this issue by:
`pip3 uninstall sha3 && pip3 install pysha3`

**Comment by todofixthis** [comment]
Ah.  Good catch!  Thanks for posting your solution!!
