### ISSUE TITLE
add optional `timeout` parameter to calls

### ISSUE THREAD

**Issue by lunfardo314** [iotaledger/iota.lib.py#201]
this improvement is needed to handle blocked requests when IRI is not synced and similar

**Comment by todofixthis** [comment]
Hey @lunfardo314 thanks for the suggestion!

`HttpAdapter` accepts an optional `timeout` argument upon initialisation (defaults to `socket.getdefaulttimeout()`):

https://github.com/iotaledger/iota.lib.py/blob/master/iota/adapter/__init__.py#L226

For example:

```python
api = Iota(HttpAdapter('http://localhost:14265', timeout=10))
```

Alternatively, you can call `socket.setdefaulttimeout()` at any time to change the default request timeout (the adapter will check it before every request).

More info:
https://github.com/iotaledger/iota.lib.py/blob/master/docs/adapters.rst#httpadapter

---

Does this address the issue you're describing, or is there another facet to the problem?

**Comment by lunfardo314** [comment]
Thank you! I been told once just lost it somewhere :) 
I think this practically allows to have timeouts on calls.
What I expected is though is to have `timeout=` argument for each call individually (or for some of them). For convenience. 
For example `get_node_info` call needs maybe some 20 sec while for `send_transfer` and other heavy calls would need significantly more. Now it seems to call `socket.setdefaulttimeout()` each time when I want to change the global default and not to forget reset it after.

By the way: is it ok to create Iota instance for each call? They are garbage collected anyway no?

**Comment by todofixthis** [comment]
Interesting.  Hm....

This would be a... novel use case for it, but you could use `RoutingWrapper` to accomplish this:

```python
from iota.adapter import HttpAdapter
from iota.adapter.wrappers import RoutingWrapper
from iota.api import Iota

# Create router with default configuration.
router = RoutingWrapper(HttpAdapter('http://localhost:14265', timeout=60))

# Customise timeout for specific commands:
router.add_route('getNodeInfo', HttpAdapter('http://localhost:14265', timeout=20))

api = Iota(router, 'SEED')
```

**Comment by lunfardo314** [comment]
Cool, never used those routing wrappers. 
That solves the problem.
As for novel use  case :) just recently iri was very unstable, sometimes blocks calls, my system stopped, had to make more intelligent timeout/exception processing to make the system running without restarts.

**Comment by todofixthis** [comment]
I originally wrote `RoutingWrapper` so that I could use a local IRI to do `attachToTangle`, but use a public node for everything else (example in the [docs](https://pyota.readthedocs.io/en/develop/adapters.html#routingwrapper)).

Never really considered what else it might be used for... but hey, I've got a hammer, and this looks an awful lot like a nail, so... 😹
