### ISSUE TITLE
iota.codecs.TrytesDecodeError: 'trytes_ascii' codec can't decode trytes WW at position 0-1: ordinal not in range(255)

### ISSUE THREAD

**Issue by purplecity** [iotaledger/iota.lib.py#209]
CODE:

```python
from iota import Iota
import subprocess

url="https://nodes.devnet.iota.org:443"
seed=subprocess.check_output("cat /dev/urandom |LC_ALL=C tr -dc 'A-Z9' | fold -w 81 | head -n 1",shell=True)
print(type(seed))
seed=seed.decode().replace("\n","")
api = Iota(url,seed)
address=api.get_new_addresses(security_level=3)
x=address["addresses"][0]
y=x.decode()
print(type(y),y)
```

ERROR:
```
iota.codecs.TrytesDecodeError: 'trytes_ascii' codec can't decode trytes WW at position 0-1: ordinal not in range(255)
```

**Comment by purplecity** [comment]
now I am ok。 flowing:

from iota import Iota
import subprocess

url="https://nodes.devnet.iota.org:443"
seed=subprocess.check_output("cat /dev/urandom |LC_ALL=C tr -dc 'A-Z9' | fold -w 81 | head -n 1",shell=True)
print(type(seed))
seed=seed.decode().replace("\n","")
api = Iota(url,seed)
address=api.get_new_addresses(security_level=3)
print(address)
x=address["addresses"][0]
y=bytes(x.address).decode()
print(type(y),y)

**Comment by todofixthis** [comment]
Hey @purplecity.  `decode()` is meant to convert a binary sequence that was previously `encode()`'d into trytes.  Addresses are generated algorithmically from the seed, so if an address is `decode()`-able, it's only by coincidence.

I feel like this might be a workaround for a different problem that you are trying to solve; what is the desired outcome for your application?

**Comment by purplecity** [comment]
thanks。I just want generate a new address and save to mysql。

**Comment by purplecity** [comment]
@todofixthis   if  user give me an 81 Trytes address(any in A-Z9).  how I check this address is valid?

**Comment by todofixthis** [comment]
Ah.  In that case, you can simply cast the `Address` object as a `str` (or `unicode` if using Python 2), and you'll have the trytes:

```python
In [1]: from iota import Iota

In [2]: api = Iota('http://localhost:14265')

In [3]: address = api.get_new_addresses(count=1, security_level=3)['addresses'][0]

In [4]: address
Out[4]: Address(b'KXIILGJANI9IIRNVKPDIZNOUTNZJCYAAFKWLSQEVFLFYMHMBEEBEYHMBDMYBEJTPDOQUHGXLUNS9UKMZX')

In [5]: str(address)
Out[5]: 'KXIILGJANI9IIRNVKPDIZNOUTNZJCYAAFKWLSQEVFLFYMHMBEEBEYHMBDMYBEJTPDOQUHGXLUNS9UKMZX'
```

If you have the string value and want to convert back into an `Address` object, simply use the constructor:

```python
In [1]: from iota import Address

In [2]: stored_address = 'KXIILGJANI9IIRNVKPDIZNOUTNZJCYAAFKWLSQEVFLFYMHMBEEBEYHMBDMYBEJTPDOQUHGXLUNS9UKMZX'

In [3]: address = Address(stored_address)

In [4]: address
Out[4]: Address(b'KXIILGJANI9IIRNVKPDIZNOUTNZJCYAAFKWLSQEVFLFYMHMBEEBEYHMBDMYBEJTPDOQUHGXLUNS9UKMZX')
```

As far as checking to see if an address is valid, it depends on what you mean by "valid" — any 81-tryte sequence is potentially a usable address in the IOTA protocol.

I think what you are asking about is, how to make sure that the user didn't make a mistake when copying/typing the address.  For this, you can use address checksums.  The checksum is an additional 9 trytes that gets appended to the address.  If even a single tryte changes, the checksum is invalid, so you know that the address is not correct.

To generate an address with a checksum, you have two options:

```python
In [1]: from iota import Iota

In [2]: api = Iota('http://localhost:14265')

# Option 1:  Pass ``checksum`` param to ``Iota.get_new_addresses()``:
In [3]: address = api.get_new_addresses(count=1, security_level=3, checksum=True)['addresses'][0]

In [4]: address
Out[4]: Address(b'DCOEFWUXLBUYUASDSQ9ZTGRFYJZFOZCPXSMO9JDCDOTZTCZBYPHQVBANGJSD9IICZLMFYDXNSEPSPJPVBHILUMOQJD')

In [5]: address.address
Out[5]: TryteString(b'DCOEFWUXLBUYUASDSQ9ZTGRFYJZFOZCPXSMO9JDCDOTZTCZBYPHQVBANGJSD9IICZLMFYDXNSEPSPJPVB')

In [6]: address.checksum
Out[6]: AddressChecksum(b'HILUMOQJD')

In [7]: address.is_checksum_valid()
Out[7]: True

# Option 2: Call the ``Address`` object's ``with_valid_checksum()`` method:
In [8]: address2 = api.get_new_addresses(count=1, security_level=3)['addresses'][0]

In [9]: address2
Out[9]: Address(b'DCOEFWUXLBUYUASDSQ9ZTGRFYJZFOZCPXSMO9JDCDOTZTCZBYPHQVBANGJSD9IICZLMFYDXNSEPSPJPVB')

In [10]: checksummed_address = address2.with_valid_checksum()

In [11]: checksummed_address
Out[11]: Address(b'DCOEFWUXLBUYUASDSQ9ZTGRFYJZFOZCPXSMO9JDCDOTZTCZBYPHQVBANGJSD9IICZLMFYDXNSEPSPJPVBHILUMOQJD')
```

**Comment by purplecity** [comment]
Dear @todofixthis  help much，sincere thanks。 I am all new about iota（look document 2 days,from non-english speaking areas,poor English） and had many problems。

Problem1: address re-use
at documention have not  ever saw the word "public key"。 only seed,private key,address. 
seed->private key -> address.my understanding is it can't derive private key from address(I wrong?) 

documents suggest don't re-use address when it had a transaction，why it would decrease the security?????    document's explanation is very confusing. could tell me an exact  way to get the private key or other privte information when re-use address？

u know it is greate inconvenience for can't re-use address 。for example 。multisign address and  other cold wallet address need  traded many times。

**Comment by purplecity** [comment]
Problem2: n of m multisig

==========================================
On https://pyota.readthedocs.io/en/latest/multisig.html:

In order to enable a 2 of 3 multisig, the cosigners need to share their private keys with the other parties in such a way that no single party can sign inputs alone, but that still enables an M-of-N multsig. In our example, the sharing of the private keys would look as follows:

Alice -> Bob

Bob -> Carol

Carol -> Alice

Now, each participant holds two private keys that he/she can use to collude with another party to successfully sign the inputs and make a transaction. But no single party holds enough keys (3 of 3) to be able to independently make the transaction.
================================

so it is mean essentiallyt to sign each private key once?? for example Alice and Bob to sign,just like this:

Alice do twice sign:
gpk_result = api_1.get_private_keys(index=0, count=1, security_level=3)
private_key_1 = gpk_result['keys'][0]  # type: PrivateKey
private_key_1.sign_input_transactions(bundle, 1)

gpk_result = api_2.get_private_keys(index=42, count=1, security_level=3)
private_key_2 = gpk_result['keys'][0]  # type: PrivateKey
private_key_2.sign_input_transactions(bundle, 4)

api_1 and api_2 is use Alice's seed and  Carol's seed


Bob do one sign:

gpk_result = api_3.get_private_keys(index=8, count=1, security_level=2)
private_key_3 = gpk_result['keys'][0]  # type: PrivateKey
private_key_3.sign_input_transactions(bundle, 7)

**Comment by purplecity** [comment]
The risk for iota's multi-signature address is if a private key is lost. You can't sign it。 because need every private key to sign transaction

**Comment by todofixthis** [comment]
Hey @purplecity since the original problem was resolved, I'm going to go ahead and close this issue.

For general questions about how IOTA's multisig protocol works, I would recommend asking on the [IOTA StackExchange site](https://iota.stackexchange.com/); this GitHub page is for reporting issues and requesting features for the PyOTA library.
