### ISSUE TITLE
Response of get_account_data takes 20 mins...

### ISSUE THREAD

**Issue by rav1112** [iotaledger/iota.lib.py#210]
While calling get_account_data it takes total 20 mins to get the response from the node. Whats the issue?

**Comment by todofixthis** [comment]
Hi @rav1112 did the response contain lots of addresses?  The slowest part of `get_account_data()` is generating addresses — the more addresses you've used from a particular seed, the more time it will take to complete this request.

If there were only a few addresses, then the issue might just be that the node you connected to is really slow for some reason; try connecting to a different node and see if the response comes back more quickly.

**Comment by todofixthis** [comment]
Hey @rav1112 it's been a little while; I'm going to go ahead and close this issue.  If you are still having problems with `get_account_data()`, feel free to re-open this issue so that we can have a look 😺
