### ISSUE TITLE
ImportError: cannot import name Iota

### ISSUE THREAD

**Issue by HunagYuCheng** [iotaledger/iota.lib.py#214]
I am trying to do something with PyOTA Documentation
i'm use Python 3.5 x64 in win 10 ,and install PyOTA in virtualenv.
I was looking for a similar problem before. #79 #123
So i tryied:
pip install --no-binary ':all:' pyota then 
I try to import Iota from iota i still had :
```
Traceback (most recent call last):
  File "iota.py", line 1, in <module>
    from iota import Iota
  File "", line 1, in <module>
    from iota import Iota
ImportError: cannot import name 'Iota'
```

I really want to do it with python 
Thank you for reading
```
Package         Version
--------------- ----------
asn1crypto      0.24.0
certifi         2018.11.29
cffi            1.11.5
chardet         3.0.4
class-registry  2.1.2
cryptography    2.4.2
filters         1.3.2
idna            2.8
pip             18.1
pycparser       2.19
pyOpenSSL       18.0.0
PyOTA           2.0.7
pysha3          1.0.2
python-dateutil 2.7.5
pytz            2018.7
regex           2018.11.22
requests        2.21.0
setuptools      40.6.3
six             1.12.0
urllib3         1.24.1
wheel           0.32.3

```

**Comment by HunagYuCheng** [comment]
sorry ,I make a big mistake.I should not set the file name to IOTA.
so the path was wrong

**Comment by crisdeodates** [comment]
I would like to reopen this request. I am also getting the same error 

> ImportError: cannot import name 'Iota'

even after double checking the installation of PyOTA. Any help in this regard is appreciated. I am a beginner to IOTA, so there is so less that I can dig deep into

**Comment by todofixthis** [comment]
Hi @crisdeodates in the case of the original issio, the problem occurred because the developer named their file `iota.py`, which conflicts with PyOTA's top-level package name `iota`.  The issue was resolved by renaming their fie to some other name.

Could you try that and see if it resolves your issue?  If not, then would you mind opening a new issue and posting the full traceback and error message?
