### ISSUE TITLE
compatibility with IRI 1.6.0-RELEASE?

### ISSUE THREAD

**Issue by bgaebel** [iotaledger/iota.lib.py#219]
Hey,

I have some problems with the newer IRI-Releases.
If a node is running IRI on version 1.6.0 I will get wrong hashes and therefore wrong values.
Every Hash is '99999999999...' in that case.
For example: a correct TransactionHash returns a wrong BundleHash after api.get_bundles(tx_hash)
The BundleHash is '9999999999999999999999...'

I found out, that every Node with this newer version has the parameter 'lastSnapshottedMilestoneIndex' in his node-info -> get_node_info()
Older Versions don't return this paramter in the list!

With Nodes running IRI 1.5.6 everything works well...
so what can be the problem?

I'm running PyOTA 2.0.7 and PyOTA-CCurl 1.0.9

**Comment by todofixthis** [comment]
Hey @bgaebel thanks for reporting this issue!  I'll ping the core devs to find out more about this.

**Comment by lzpap** [comment]
Hey @bgaebel , this issue has been solved with newer IRI releases, right?
