### ISSUE TITLE
How to get all the transactions in tangle?

### ISSUE THREAD

**Issue by rav1112** [iotaledger/iota.lib.py#223]
Need to get all transaction not any specific wallet

**Comment by todofixthis** [comment]
Hey @rav1112 this probably goes beyond the scope of what PyOTA can deliver — IRI nodes don't expose this kind of firehose via the HTTP API.

There's a project by @mlouielu that implements an IRI node in Python, which might have the functionality that you're looking for:
https://github.com/mlouielu/iota-python

**Comment by mlouielu** [comment]
@rav1112 you can take a look if iota-python still can work, if everything is correct, you can get all the transaction in rocksdb by iota-python. But I didn't test it on latest IRI, you will need to try it out yourself :)

**Comment by lzpap** [comment]
Hey @rav1112 did you find the answer to your question? May I close the issue?
