### ISSUE TITLE
ImportError: cannot import name '_np_version_under1p16'

### ISSUE THREAD

**Issue by shivampatel16** [iotaledger/iota.lib.py#230]
```py
import pandas as pd

df = pd.read_csv("bbb.csv", header = None)
#df = pd.read_csv("bbb.csv", engine = 'python', header = None)

df.head()
```

This leads me to the following error:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-34-1063cb31b5ae> in <module>()
----> 1 import pandas as pd
      2 
      3 df = pd.read_csv("bbb.csv", header = None)
      4 #df = pd.read_csv("bbb.csv", engine = 'python', header = None)
      5 

~\Anaconda3\lib\site-packages\pandas\__init__.py in <module>()
     20 
     21 # numpy compat
---> 22 from pandas.compat.numpy import (
     23     _np_version_under1p14,
     24     _np_version_under1p15,

ImportError: cannot import name '_np_version_under1p16'
```

**Comment by todofixthis** [comment]
Hi @shivampatel16 it seems to me like the `pandas` lib is not installed correctly in your virtualenv.  Try reinstalling it, and be sure to pay special attention if any compilation errors are reported during the installation process.

I need to close this issue, as it does not appear to be related to PyOTA.  If you are continuing to experience this issue, I recommend asking on [StackOverflow](https://stackoverflow.com/questions/tagged/pandas) or on the [pandas issue tracker](https://github.com/pandas-dev/pandas/issues).
