### ISSUE TITLE
Update the core commands to match the latest IRI 1.8.1 release

### ISSUE THREAD

**Issue by pdecol** [iotaledger/iota.lib.py#235]
The core commands implement the API endpoints which are provided by IRI and are contained in the `StrictIota` class. I compared the current implementation with the latest IRI 1.8.1 release (https://github.com/iotaledger/iri/blob/v1.8.1-RELEASE/src/main/java/com/iota/iri/service/API.java). The following changes are needed to get `StrictIota` up to date. 

Missing commands:
- **getNodeAPIConfiguration:** This will be needed for #138
- **getMissingTransactions**

Missing parameters:
- **getBalances**: `tips` is missing as an optional parameter. `references` is new in the response and could be added to the response filter.
- **getTransactionsToApprove:**  `references` is missing as an optional parameter.

Changed fields in the response:
- **getBalances**: `milestone` (type: `Address`) get removed and `milestoneIndex` (type: `int`)  got added to the response. Shall we remove `milestone`? Or keep both to ensure backwards compatibility?

Fields that I would add to the response filter because without these values in the response the API call is useless:
- **wereAddressesSpentFrom**:  `states`
- **checkConsistency:** `state`

Furthermore for all commands :
- In the source code are references to https://iota.readme.io/docs/  As this website is not used anymore this should be updated to respective references in the official docs https://docs.iota.org/docs/node-software/0.1/iri/references/api-reference

Let me know what you think. I planning to implement this myself and I will open a pull request soon.

**Comment by todofixthis** [comment]
Wow, this is amazing!  😻 Thanks @pdecol !

**Comment by GalRogozinski** [comment]
The IRI team needs this issue fixed for our regression tests.
