### ISSUE TITLE
IRI version compatibility check at startup

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/iota.lib.py#25]
Add a method to `StrictIota` that will perform a compatibility check (i.e., verify IRI version >= 1.1.2.4 (see https://github.com/iotaledger/iota.lib.py/releases/tag/1.1.0 for more info)).

If the compatibility check fails, raise an exception.  If the user wants to connect to a node running an old version of the software, they can specify it in the `__init__` method (see note below).

## Notes:
- Add an optional parameter to `__init__` to enable/configure the automatic compat check.
    - By default, this is set to a constant.
    - Set to `None` to disable the check.
    - Set to a version string to specify the version number to use for comparison.
- Defer this check until the first time the code initiates a request, and piggyback if the request is `getNodeInfo`.

Examples:

```python
>>> iota = Iota(...)
>>> iota.get_transfers(...)
# Issue `getNodeInfo` command here and perform compatibility check.
```

```python
>>> iota = Iota(...)
>>> iota.get_node_info()
# Execute `getNodeInfo` as normal, but perform compatibility check before returning result.
```

```python
>>> iota = Iota(..., require_node_version=None)
>>> iota.get_transfers(...)
# No compatibility check performed.
```

```python
>>> iota = Iota(..., require_node_version='1.2.1')
>>> iota.get_transfers(...)
# Issue `getNodeInfo` and check for IRI version >= 1.2.1 before continuing.
```

**Comment by todofixthis** [comment]
Note: It may be better to wait until IOTA Production Implementation is released before starting on this.

**Comment by szepnapot** [comment]
Is this relevant now?

**Comment by todofixthis** [comment]
Aye, I think it's still relevant — for example, the client should warn if trying to connect to a node that hasn't been upgraded to 1.4.1 yet (I think that is the version of the IRI software that introduces Curl-P-81).

The only open question in my mind is, what happens when someone writes their own node software with its own versioning scheme.  But, there are ways around this (e.g., `getNodeInfo` also returns the version of the IOTA protocol that the node conforms to, rather than the version number of the node software).

**Comment by todofixthis** [comment]
This functionality is now implemented, but in reverse 😸 

The IRI node now requires the client to send an `X-IOTA-API-VERSION` header with each request, and the IRI will reject any request where the value of that header indicates an incompatible API version.

See #84 for more info.
