### ISSUE TITLE
hello_world.py fails out-of-the-box (defaults udp://)

### ISSUE THREAD

**Issue by alon-e** [iotaledger/iota.lib.py#29]
In example/hello_world.py - the default URI is `udp://localhost:14265/`
This will cause an error:
```  
File "/home/alon/iota/iota.lib.py/iota/adapter/__init__.py", line 97, in resolve_adapter
    'uri':    uri,
iota.adapter.InvalidUri: Unrecognized protocol u'udp'.
```

should be: `default = 'http://localhost:24265/' `
It's probably a typo/left-over, but is the first user's experience.

**Comment by todofixthis** [comment]
Ooh.  Completely missed that.  Thanks @alon-e!

**Comment by todofixthis** [comment]
Fixed in next release.  Thanks for the heads-up!
