### ISSUE TITLE
Method to check to see if a transaction can be reattached to the Tangle

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/iota.lib.py#38]
From <https://github.com/iotaledger/iota.lib.js#isreattachable> (with a few modifications):

> ### `isReattachable`
> 
> This API function helps you to determine whether you should replay a transaction or make a  completely new transaction with a different seed. What this function does, is it takes one or more input addresses (i.e. from spent transactions) as input and then checks whether any transactions with a value transferred are confirmed. If yes, it means that this input address has already been successfully used in a different transaction and as such you should no longer replay the transaction.

#### Input
```python
api = Iota(...)
ir_result = api.is_reattachable(addresses)
```
- **`addresses`**: `Iterable[Address]` input addresses from the transaction(s).

#### Returns
`{'reattachable': List[bool]}` — similar to `getBalances`, the result contains a list of booleans corresponding to the addresses that were provided in the request.

**Comment by todofixthis** [comment]
Not sure about the name — `check_input_spendability` or similar may be a more accurate indication of what this method does.

**Comment by todofixthis** [comment]
This method is also really important for security because Winternitz signatures become exponentially less secure after each re-use.

**Comment by todofixthis** [comment]
Note:  In the latest version of the JS lib, this method was renamed to `isReattachable` and accepts multiple addresses now.  I've updated the issue description.

**Comment by jinnerbichler** [comment]
Opened a PR #108 :)

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.4

Thanks Johannes!!
