### ISSUE TITLE
Incorrect attribute names in GetBalancesCommand response (using sandbox example script)

### ISSUE THREAD

**Issue by johngrantuk** [iotaledger/iota.lib.py#55]
PyOTA 1.1.3

Python 2.7.10

Mac OS El Capitan 10.11.6

**Description:**
Running sandbox [example](https://github.com/iotaledger/iota.lib.py/blob/master/examples/sandbox.py). iota.send_transfer gives following error: TypeError: 'NoneType' object is not iterable

**Traceback:**
Traceback (most recent call last):
  File "sandbox.py", line 51, in <module>
    message = TryteString.from_string('Hello, Tangle!'),
  File "/Users/johngrant/Downloads/iota/env/lib/python2.7/site-packages/iota/api.py", line 822, in send_transfer
    minWeightMagnitude  = min_weight_magnitude,
  File "/Users/johngrant/Downloads/iota/env/lib/python2.7/site-packages/iota/commands/__init__.py", line 122, in __call__
    self.response = self._execute(self.request)
  File "/Users/johngrant/Downloads/iota/env/lib/python2.7/site-packages/iota/commands/extended/send_transfer.py", line 46, in _execute
    transfers       = transfers,
  File "/Users/johngrant/Downloads/iota/env/lib/python2.7/site-packages/iota/commands/__init__.py", line 122, in __call__
    self.response = self._execute(self.request)
  File "/Users/johngrant/Downloads/iota/env/lib/python2.7/site-packages/iota/commands/extended/prepare_transfer.py", line 54, in _execute
    threshold = want_to_spend,
  File "/Users/johngrant/Downloads/iota/env/lib/python2.7/site-packages/iota/commands/__init__.py", line 122, in __call__
    self.response = self._execute(self.request)
  File "/Users/johngrant/Downloads/iota/env/lib/python2.7/site-packages/iota/commands/extended/get_inputs.py", line 62, in _execute
    for i, balance in enumerate(gb_response['balances']):
TypeError: 'NoneType' object is not iterable

**Possible fix? (Creating a Pull request)**
In get_inputs.py, Line 51, gb_response = GetBalancesCommand( ) is returning: {u'MilestoneIndex': 123423, …. u'Duration': 0, u'Balances': [0, 0, 41, 0, 0, 0]}

Line 62 uses: enumerate(gb_response['balances'])

Changing 'balances' to 'Balances' seems to fix the problem.

**Comment by todofixthis** [comment]
Hi @johngrantuk!  Thanks for reporting this issue!

This looks like a problem with the sandbox node.  Could I ask you to collect a little extra debugging info?

Please run the following commands:

```
from iota import *
from iota.adapter.sandbox import SandboxAdapter

iota =\
  Iota(
    adapter = SandboxAdapter(
      uri = 'https://sandbox.iota.org/api/v1/',

      # Replace with your auth token.
      auth_token = 'auth token goes here',
    ),
  )

import logging, sys
logging.basicConfig(level=logging.DEBUG, stream=sys.stderr)
iota.api.set_logger(logging.getLogger(__name__))

iota.get_balances([b'A'])
```

You can scrub out your auth token if it appears in the debug output; what I'm most interested in is the raw response payload from the sandbox.  It appears that the sandbox is incorrectly capitalising the attribute names, but I need to confirm.

**Comment by johngrantuk** [comment]
I had to add from __future__ import absolute_import, division, print_function, unicode_literals otherwise I got "AttributeError: 'str' object has no attribute 'scheme'". With this added the output is:

Traceback (most recent call last):
  File "debug.py", line 18, in <module>
    iota.api.set_logger(logging.getLogger(__name__))
  File "/Users/johngrant/Downloads/iota/env/lib/python2.7/site-packages/iota/api.py", line 103, in __getattr__
    command = command,
iota.api.InvalidCommand: Iota does not support 'api' command.

**Comment by todofixthis** [comment]
Ahhh, shoot.  Sorry about that; I copied the wrong command.  It should be iota.**adapter**.set_logger.  This is the corrected code:

```python
from iota import *
from iota.adapter.sandbox import SandboxAdapter

iota =\
  Iota(
    adapter = SandboxAdapter(
      uri = u'https://sandbox.iota.org/api/v1/',

      # Replace with your auth token.
      auth_token = 'auth token goes here',
    ),
  )

import logging, sys
logging.basicConfig(level=logging.DEBUG, stream=sys.stderr)
iota.adapter.set_logger(logging.getLogger(__name__))

iota.get_balances([b'A'])
```

**Comment by johngrantuk** [comment]
All good. New output below:

DEBUG:__main__:Sending post to https://sandbox.iota.org/api/v1/commands: '{"threshold": 100, "command": "getBalances", "addresses": ["A99999999999999999999999999999999999999999999999999999999999999999999999999999999"]}'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sandbox.iota.org
DEBUG:urllib3.connectionpool:https://sandbox.iota.org:443 "POST /api/v1/commands HTTP/1.1" 200 150
DEBUG:__main__:Receiving post from https://sandbox.iota.org/api/v1/commands: '{"Duration":0,"Balances":[0],"Milestone":"SYMOPFBXCXQMLGKKCVX9NFZCIBDRIKPRJFPASJYHWPYPVFEOUMZABQLRXJMETXCDDBOVLDTPOZDL99999","MilestoneIndex":127002}\n'

**Comment by todofixthis** [comment]
Thanks John!

Hmm... that's interesting.  Looks like the sandbox node is using the wrong case for attribute names in the response after all.

I'm-a ping Dom about this to see if this is an issue with the sandbox, or if the attribute names changed in a recent version of the IRI.  As soon as I find out what's up, fixing this issue will be top priority.

**Comment by jinnerbichler** [comment]
Any news on this one?

According to the `getNodeInfo` the IRI version of the sandbox is 1.4.0.

Calling `getBalances` on the sandbox returns
```
{
    "Duration": 0,
    "Balances": [0],
    "Milestone": "RXTDTARWZPYTWBFXDHGZDTCDYBWGMKAHDKIAYKKKGUTUNJAXIVIKYDVCTVE9WGJ9GAPFCEZOFYZPA9999",
    "MilestoneIndex": 233555
}
```

whereas running IRI v.1.4.0 locally (either via Java or Docker) returns
```
{
    "duration": 6,
    "balances": ["0"],
    "milestone": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
    "milestoneIndex": 217000
}
```

There is definitely a difference. The first letter of each JSON key is capitalised. There might be an issue with the JSON serialiser at the sandbox runtime.

**Comment by todofixthis** [comment]
Hey guys.  Sorry that this is taking so long to resolve!  I've logged a couple of issues with the Sandbox and Go projects, and I bugged the IF folks again.

Keep an eye on these issues:

- https://github.com/iotaledger/sandbox/issues/7
- https://github.com/iotaledger/iota.lib.go/issues/11

**Comment by todofixthis** [comment]
I'm going to go ahead and close this issue, as it's not really a problem with PyOTA.  Do keep an eye on the issues linked in the previous comment; if necessary, we can escalate this with the sandbox/iri teams on Discord.
