### ISSUE TITLE
Address generate - checksum missing

### ISSUE THREAD

**Issue by kasaram** [iotaledger/iota.lib.py#64]
Hi I created IOTA address from seed using below code. But generated address are 81 char length. cannot able to send IOTA to those address. checksum is missing. how to generate Address with check sum in pyota?

```python
from iota import Iota
seed = 'seed here'
api = Iota('https://n1.iota.nu:443', seed=seed)
addresses = api.get_new_addresses(index=0, count=2)
for key in addresses:
    for addr in addresses[key]:
        print addr
```

**Comment by todofixthis** [comment]
Hey @kasaram to add a checksum, invoke each address' `with_valid_checksum` method:

```python
    for addr in addresses[key]:
        print(addr.with_valid_checksum())
```
