### ISSUE TITLE
examples/address_generator.py outputs incorrect addresses when --count is None

### ISSUE THREAD

**Issue by cychotic** [iotaledger/iota.lib.py#66]
In branch feature/kerl using examples.address_generator.py,

If --count is None, it outputs the wrong address.

**Comment by todofixthis** [comment]
Hey @cychotic thanks for the heads-up!  Could you include some example addresses?

**Comment by cychotic** [comment]
I apologize.   I retested it again and it is actually working as intended.  I was comparing it to the wrong last address because I attached it already.   The code is correctly generating the first unused address.

**Comment by todofixthis** [comment]
Cool, thanks for confirming!
