### ISSUE TITLE
Attachment Timestamps

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/iota.lib.py#67]
In a recent snapshot, the structure of IOTA transactions has changed a bit:

- Rename `tag` to `legacy_tag`.
- Add `tag`, `attachment_timestamp` , `attachment_timestamp_lower_bound` and `attachment_timestamp_upper_bound` after `branch_transaction`.
- Resize `nonce` from 81 to 27 trytes.

More info:
- https://github.com/iotaledger/iri/pull/303
- https://github.com/iotaledger/iota.lib.js/pull/79/files

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.1

**Comment by PhotographerGuo** [comment]
Could explain more about the "attachmentTimestamp", who add it to the snapshot raw data? 
I know the "timestamp" is made by the user who sends the tx to the Tangle. But as for "attachmentTimestamp", the user does not know when the tx is confirmed then they can not edit it, right?
