### ISSUE TITLE
transfer = ProposedTransaction(...) naming convention doesn't follow other libs

### ISSUE THREAD

**Issue by alon-e** [iotaledger/iota.lib.py#72]
both in `iota.lib.js` and `iota.lib.java` there are explicit `transfer` objects.
[iota.lib.js](https://github.com/iotaledger/iota.lib.js/blob/master/lib/api/api.js#L1024)
[iota.lib.java](https://github.com/iotaledger/iota.lib.java/blob/master/src/main/java/jota/IotaAPI.java#L366)

however, in `iota.lib.py` these objects are constructed with `iota.ProposedTransaction(...)`, which is also used as an intermediary representation of [transactions](https://github.com/iotaledger/iota.lib.py/blob/master/iota/transaction/creation.py#L28) & bundles.
from examples:
https://github.com/iotaledger/iota.lib.py/blob/master/examples/send_transfer.py#L24

this is confusing for users moving from other library implementations. like myself. :)

---
I propose a new class named `Transfer`, that inherits from `ProposedTransaction` and is functionally the same, but adheres to the naming conventions of the other libs. (without breaking code that already uses `ProposedTransaction` of course).

**Comment by todofixthis** [comment]
Hey Alon!  Sounds reasonable to me.  I'll add it to the 2.0.x branch.

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.1
