### ISSUE TITLE
Port documentation to Sphinx

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/iota.lib.py#78]
We need your help to port the existing documentation from Markdown to reStructuredText so that we can publish it on [ReadTheDocs](http://pyota.readthedocs.io/en/develop/)!

The Markdown files are located here:
https://github.com/iotaledger/documentation/tree/iota.lib.py/1.2.x/source/includes

These need to be copied into the PyOTA repository and converted to reStructuredText here:
https://github.com/iotaledger/iota.lib.py/tree/develop/docs

Note:  This is a big project, and multiple people might end up working on this.  Please be sure to post here so that you can coordinate with others, to avoid duplicating work.

If you are not familiar with Sphinx and/or reStructuredText, here's a quickstart:

1. Install PyOTA locally.
2. `pip install sphinx`
3. `cd docs`
4. `make html`
    * This will generate the static HTML documentation.  You can then open `docs/_build/html/index.html` in your browser to see what it will (sort of) look like when it is published to RTD.
5. To make changes to the documentation, edit the corresponding `.rst` file, and then do another `make html`.

**Important:** If you add a new `.rst` file, be sure to update the `toctree` directive in `index.rst`!

Here are some references for reStructuredText directives and markup syntax (once you get used to it, you will never want to go back to Markdown 😸):
- http://docutils.sourceforge.net/docs/user/rst/quickref.html
- http://docutils.sourceforge.net/docs/ref/rst/directives.html
- http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html

You can also use this online rst editor to try stuff out:
http://rst.ninjs.org/

**Comment by QuantumDamage** [comment]
I'm starting to work on this issue.

**Comment by QuantumDamage** [comment]
@todofixthis I see that there is already **types.rst** doc file. Should I overwrite it with content from **_types.md** file?

**Comment by todofixthis** [comment]
@QuantumDamage Affirmative.  It might be partially-complete using `_types.md` as the source, so you might be able to leave some/all of what's already there.

**Comment by QuantumDamage** [comment]
@todofixthis OK.

**Comment by QuantumDamage** [comment]
#102

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.3

Thank you!!!
