### ISSUE TITLE
Updates for compatibility with IRI 1.4.1

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/iota.lib.py#84]
IRI v1.4.1 was released yesterday, and all API libraries need some changes to be compatible:

- Include `X-IOTA-API-Version: 1` header with each API request (see https://github.com/iotaledger/iota.lib.js/commit/3c0973bf93a7385cba97f5492cbed4fd5f7dd954).
- Insecure bundle detection when signing (see https://github.com/iotaledger/iota.lib.js/blob/v0.4.2/lib/crypto/bundle/bundle.js#L119-L125).
    - Note:  applies _only_ when signing a bundle; does not apply when validating signatures.

**Comment by lacicloud** [comment]
Temporary fix for those who are looking is to edit the file https://github.com/iotaledger/iota.lib.py/blob/master/iota/adapter/__init__.py : after line 268, add
kwargs['headers']['X-IOTA-API-Version'] = 'ANY' 

Keep up the good work @todofixthis !

**Comment by todofixthis** [comment]
I believe we can use this as a test case for the insecure bundle detection:

```javascript
> var b = new Bundle();
> b.addEntry(1, '9XV9RJGFJJZWITDPKSQXRTHCKJAIZZY9BYLBEQUXUNCLITRQDR9CCD99AANMXYEKD9GLJGVB9HIAGRIBQ', 0, 'PPDIDNQDJZGUQKOWJ9JZRCKOVGP', 1509136296, 0)
undefined
> b.finalize()
undefined
> b.bundle[0]
{ address: '9XV9RJGFJJZWITDPKSQXRTHCKJAIZZY9BYLBEQUXUNCLITRQDR9CCD99AANMXYEKD9GLJGVB9HIAGRIBQ',
  value: 0,
  obsoleteTag: 'ZTDIDNQDJZGUQKOWJ9JZRCKOVGP',
  tag: 'PPDIDNQDJZGUQKOWJ9JZRCKOVGP',
  timestamp: 1509136296,
  currentIndex: 0,
  lastIndex: 0,
  bundle: 'NYSJSEGCWESDAFLIFCNJFWGZ9PCYDOT9VCSALKBD9UUNKBJAJCB9KVMTHZDPRDDXC9UFJQBJBQFUPJKFC' }
```

Checking with core devs just to make sure I'm on the right track.

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.1
