### ISSUE TITLE
Iota.get_new_addresses() function doesn't have a checksum option

### ISSUE THREAD

**Issue by danboard-7050** [iotaledger/iota.lib.py#89]
JS API's get_new_addresses() function has a checksum option, but Python APIs' doesn't have it.

**Comment by mlouielu** [comment]
Why will you need to use checksum option? After get_new_address(), it will return a `iota.Address`, if you want to get the address with checksum, use `iota.Address.with_valid_checksum()`

**Comment by danboard-7050** [comment]
I see. Thanks.

**Comment by todofixthis** [comment]
I'm going to go ahead and re-open this.  A lot of users have been asking about it, and we should try to make the Python lib resemble the JS lib, at least a little bit (:

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.3
