### ISSUE TITLE
Add offset and length argument to pycurl absorb and squeeze

### ISSUE THREAD

**Issue by mlouielu** [iotaledger/iota.lib.py#92]
Currently, pycurl absorb and squeeze only have `trits` argument, but `pykerl` have offset and length.

Although pycurl is a deprecated hash function, but in IRI snapshot, it used `CURLP81` to sign the snapshot, so if we want to verify snapshot signature, we will need offset and length argument to used `absorb` and `squeeze`.

**Comment by todofixthis** [comment]
Hey @mlouielu thanks for reporting this!

Looks fairly straightforward to implement this; I'm going to tag this issue with `help wanted`.

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.4
