### ISSUE TITLE
Implement `find_transaction_objects` command

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/iota.lib.py#99]
The JS lib has a [command called `findTransactionObjects`](https://github.com/iotaledger/iota.lib.js/blob/v0.4.4/lib/api/api.js#L410-L431).

This is basically just a wrapper for `findTransactions` that runs the resulting hashes through `getTrytes` and `transactionObject`.

PyOTA has basically the same thing at `iota.commands.extended.utils.find_transaction_objects`; all we need to do is convert this into a proper Command class, and add some unit tests.

**Comment by lzpap** [comment]
Thanks for the implementation @pdecol !
